// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace QuantumServicesAPI.Features.GRPCService.PCProgrammingPrototype._04ProductIdentification
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ProductIdentification Success")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ProductIdentificationSuccessFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/GRPCService/PCProgrammingPrototype/04ProductIdentification", "ProductIdentification Success", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ProductIdentificationSuccess.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01Test Case ID 1809234: [Avalon Service] Verify PCBAPartNumber API Returns the PC" +
            "BA Part Number When Requested")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _01TestCaseID1809234AvalonServiceVerifyPCBAPartNumberAPIReturnsThePCBAPartNumberWhenRequested()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01Test Case ID 1809234: [Avalon Service] Verify PCBAPartNumber API Returns the PC" +
                    "BA Part Number When Requested", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
 await testRunner.WhenAsync("Send a request to the PCBAPartNumber with connected device", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.ThenAsync("API returns the PCBA part number of the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02Test Case ID 1809245: [Avalon Service] Verify PlatformName API Returns Platform" +
            " Name Starting with \'C\' for Coyote Chip")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _02TestCaseID1809245AvalonServiceVerifyPlatformNameAPIReturnsPlatformNameStartingWithCForCoyoteChip()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02Test Case ID 1809245: [Avalon Service] Verify PlatformName API Returns Platform" +
                    " Name Starting with \'C\' for Coyote Chip", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
 await testRunner.WhenAsync("Send a request to the PlatformName API with a connected device", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
 await testRunner.ThenAsync("API returns the hardware platform name, which starts with \"C\" for a Coyote chip", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03Test Case ID 1809252: [Avalon Service] Verify SerialNumber API Returns the Devi" +
            "ce Serial Number on Valid Request")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _03TestCaseID1809252AvalonServiceVerifySerialNumberAPIReturnsTheDeviceSerialNumberOnValidRequest()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03Test Case ID 1809252: [Avalon Service] Verify SerialNumber API Returns the Devi" +
                    "ce Serial Number on Valid Request", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
 await testRunner.WhenAsync("Send a request to the SerialNumber API to read the current serial number", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
 await testRunner.ThenAsync("API returns the serial number of the connected device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04Test Case ID 1809250: [Avalon Service] Verify SerialNumber API Successfully Wri" +
            "tes Serial Number to the Device")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _04TestCaseID1809250AvalonServiceVerifySerialNumberAPISuccessfullyWritesSerialNumberToTheDevice()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04Test Case ID 1809250: [Avalon Service] Verify SerialNumber API Successfully Wri" +
                    "tes Serial Number to the Device", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
 await testRunner.WhenAsync("Send a request to the SerialNumber API with a valid serial number", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
 await testRunner.ThenAsync("API writes the serial number to the device and return status as \"Success\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05Test Case ID 1809265: [Avalon Service] Verify FittingSide API Returns the Curre" +
            "nt Fitting Side of the Device")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _05TestCaseID1809265AvalonServiceVerifyFittingSideAPIReturnsTheCurrentFittingSideOfTheDevice()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("05Test Case ID 1809265: [Avalon Service] Verify FittingSide API Returns the Curre" +
                    "nt Fitting Side of the Device", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
 await testRunner.WhenAsync("Send a request to the FittingSide API to read the current fitting side from the d" +
                        "evice", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("API returns the fitting side of the connected device (Ex: Left or Right)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06Test Case ID 1809262: [Avalon Service] Verify FittingSide API Successfully Writ" +
            "es the Fitting Side to the Device")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _06TestCaseID1809262AvalonServiceVerifyFittingSideAPISuccessfullyWritesTheFittingSideToTheDevice()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("06Test Case ID 1809262: [Avalon Service] Verify FittingSide API Successfully Writ" +
                    "es the Fitting Side to the Device", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
 await testRunner.WhenAsync("Send a request to the FittingSide API with a valid fitting side (Ex: Left or Righ" +
                        "t)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
 await testRunner.ThenAsync("API writes the fitting side to the device and returns status as \"success\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07Test Case ID 1809275: [Avalon Service] Verify ProximityNetworkAddress API Succe" +
            "ssfully Returns the Network Address from the Device")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _07TestCaseID1809275AvalonServiceVerifyProximityNetworkAddressAPISuccessfullyReturnsTheNetworkAddressFromTheDevice()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("07Test Case ID 1809275: [Avalon Service] Verify ProximityNetworkAddress API Succe" +
                    "ssfully Returns the Network Address from the Device", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 44
 await testRunner.WhenAsync("Send a request to the ProximityNetworkAddress API to read the current network add" +
                        "ress from the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
 await testRunner.ThenAsync("API returns the network address of the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08Test Case ID 1810697: [Avalon Service] Verify ProductIdentity API Successfully " +
            "Verifies Product Identity With Valid Inputs")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _08TestCaseID1810697AvalonServiceVerifyProductIdentityAPISuccessfullyVerifiesProductIdentityWithValidInputs()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("08Test Case ID 1810697: [Avalon Service] Verify ProductIdentity API Successfully " +
                    "Verifies Product Identity With Valid Inputs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
 await testRunner.WhenAsync("Send a request with valid BleId, correct Brand, and private label code", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
 await testRunner.ThenAsync("API verifies that the input values match those in the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09Test Case ID 1810702: [Avalon Service] Verify API Successfully Writes MFI Brand" +
            ", Family, Model, and GAP Device Name to GATT Database")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _09TestCaseID1810702AvalonServiceVerifyAPISuccessfullyWritesMFIBrandFamilyModelAndGAPDeviceNameToGATTDatabase()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("09Test Case ID 1810702: [Avalon Service] Verify API Successfully Writes MFI Brand" +
                    ", Family, Model, and GAP Device Name to GATT Database", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
 await testRunner.WhenAsync("Send a request with valid values for MFI brand, MFI family, MFI model, and GAP de" +
                        "vice name", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
 await testRunner.ThenAsync("API writes the values to the GATT database successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10Test Case ID 1810706: [Avalon Service] [HI Automation] Verify GNOSRegistrationD" +
            "ata API Returns Data in XML Format Successfully")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _10TestCaseID1810706AvalonServiceHIAutomationVerifyGNOSRegistrationDataAPIReturnsDataInXMLFormatSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("10Test Case ID 1810706: [Avalon Service] [HI Automation] Verify GNOSRegistrationD" +
                    "ata API Returns Data in XML Format Successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
 await testRunner.WhenAsync("Send a request to the GNOSRegistrationData API to retrieve GNOS registration data" +
                        " from the hearing instrument", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
 await testRunner.ThenAsync("API returns the GNOS registration data in valid XML format", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11Test Case ID 1809277: [Avalon Service] Verify DateModified API Successfully Ret" +
            "urns the Modified Date from the Device")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _11TestCaseID1809277AvalonServiceVerifyDateModifiedAPISuccessfullyReturnsTheModifiedDateFromTheDevice()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("11Test Case ID 1809277: [Avalon Service] Verify DateModified API Successfully Ret" +
                    "urns the Modified Date from the Device", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
 await testRunner.WhenAsync("Send a request to the DateModified API to read the modified date from the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
 await testRunner.ThenAsync("API returns the modified date of the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12Test Case ID 1809280: [Avalon Service] Verify OptionsForDevice API Returns Curr" +
            "ent Device Options Successfully")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _12TestCaseID1809280AvalonServiceVerifyOptionsForDeviceAPIReturnsCurrentDeviceOptionsSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("12Test Case ID 1809280: [Avalon Service] Verify OptionsForDevice API Returns Curr" +
                    "ent Device Options Successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
 await testRunner.WhenAsync("Send a request to the OptionsForDevice API to retrieve current device options", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
 await testRunner.ThenAsync("API returns the device options of the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13Test Case ID 1809279: [Avalon Service] Verify OptionsForDevice API Writes Devic" +
            "e Options Successfully")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _13TestCaseID1809279AvalonServiceVerifyOptionsForDeviceAPIWritesDeviceOptionsSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("13Test Case ID 1809279: [Avalon Service] Verify OptionsForDevice API Writes Devic" +
                    "e Options Successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 80
 await testRunner.WhenAsync("Send a request to the OptionForDevice API with a valid integer related to device " +
                        "options", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
 await testRunner.ThenAsync("API writes the device options to the device successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14Test Case ID 1809282: [Avalon Service] Verify PrivateLabelCode API Returns Curr" +
            "ent Private Label Code Successfully")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _14TestCaseID1809282AvalonServiceVerifyPrivateLabelCodeAPIReturnsCurrentPrivateLabelCodeSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("14Test Case ID 1809282: [Avalon Service] Verify PrivateLabelCode API Returns Curr" +
                    "ent Private Label Code Successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 86
 await testRunner.WhenAsync("Send a request to the PrivateLabelCode API to retrieve the private label code", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
 await testRunner.ThenAsync("API returns the private label code of the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15Test ID Case 1809281: [Avalon Service] Verify PrivateLabelCode API Writes Priva" +
            "te Label Code Successfully")]
        [NUnit.Framework.CategoryAttribute("ProductIdentification")]
        public async global::System.Threading.Tasks.Task _15TestIDCase1809281AvalonServiceVerifyPrivateLabelCodeAPIWritesPrivateLabelCodeSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "ProductIdentification"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("15Test ID Case 1809281: [Avalon Service] Verify PrivateLabelCode API Writes Priva" +
                    "te Label Code Successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 90
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
 await testRunner.WhenAsync("Send a request to the PrivateLabelCode API with a valid integer relayed to the pr" +
                        "ivate label code", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
 await testRunner.ThenAsync("API writes the private label code to the device successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
