// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace QuantumServicesAPI.Features.GRPCService.PCProgrammingPrototype._05SecurityCertificates
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SecurityCertificates Fail")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SecurityCertificatesFailFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/GRPCService/PCProgrammingPrototype/05SecurityCertificates", "SecurityCertificates Fail", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SecurityCertificatesFail.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01Test Case ID 1810747: [Avalon Service] Verify ModelInPricePointCertificate API " +
            "Returns ValidCertModelMismatch When BleId Does Not Match")]
        [NUnit.Framework.CategoryAttribute("SecurityCertificates")]
        public async global::System.Threading.Tasks.Task _01TestCaseID1810747AvalonServiceVerifyModelInPricePointCertificateAPIReturnsValidCertModelMismatchWhenBleIdDoesNotMatch()
        {
            string[] tagsOfScenario = new string[] {
                    "SecurityCertificates"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01Test Case ID 1810747: [Avalon Service] Verify ModelInPricePointCertificate API " +
                    "Returns ValidCertModelMismatch When BleId Does Not Match", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table27.AddRow(new string[] {
                            "2400801508"});
#line 7
 await testRunner.WhenAsync("Load a valid image with a BleId that differs from the device’s BleId, and send th" +
                        "e request to the ModelInPricePointCertificate API", ((string)(null)), table27, "When ");
#line hidden
#line 10
 await testRunner.ThenAsync("API returns status for ModelInPricePointCertificate \'ValidCertModelMismatch\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02Test Case 1810755: [Avalon Service] Verify DeviceFamilyCertificateValidity API " +
            "Returns False When Certificate in Device Is Invalid")]
        [NUnit.Framework.CategoryAttribute("SecurityCertificates")]
        public async global::System.Threading.Tasks.Task _02TestCase1810755AvalonServiceVerifyDeviceFamilyCertificateValidityAPIReturnsFalseWhenCertificateInDeviceIsInvalid()
        {
            string[] tagsOfScenario = new string[] {
                    "SecurityCertificates"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02Test Case 1810755: [Avalon Service] Verify DeviceFamilyCertificateValidity API " +
                    "Returns False When Certificate in Device Is Invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table28.AddRow(new string[] {
                            "2400801508"});
#line 14
 await testRunner.WhenAsync("Send a request to the DeviceFamilyCertificateValidity API when the device contain" +
                        "s an invalid Device Family Certificate.", ((string)(null)), table28, "When ");
#line hidden
#line 17
 await testRunner.ThenAsync("API returns status for DeviceFamilyCertificateValidity \'False\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03Test Case 1810751: [Avalon Service] Verify PricePointCertificateValidity API Re" +
            "turns False When Certificate in Device Is Invalid")]
        [NUnit.Framework.CategoryAttribute("SecurityCertificates")]
        public async global::System.Threading.Tasks.Task _03TestCase1810751AvalonServiceVerifyPricePointCertificateValidityAPIReturnsFalseWhenCertificateInDeviceIsInvalid()
        {
            string[] tagsOfScenario = new string[] {
                    "SecurityCertificates"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03Test Case 1810751: [Avalon Service] Verify PricePointCertificateValidity API Re" +
                    "turns False When Certificate in Device Is Invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table29.AddRow(new string[] {
                            "2400801508"});
#line 23
 await testRunner.WhenAsync("Send a request to the PricePointCertificateValidity API when the device has an in" +
                        "valid Price Point Certificate", ((string)(null)), table29, "When ");
#line hidden
#line 26
 await testRunner.ThenAsync("API returns status for PricePointCertificateValidity \'False\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
