// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace QuantumServicesAPI.Features.GRPCService.PCProgrammingPrototype._03DeviceImage
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DeviceImage Fail")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class DeviceImageFailFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/GRPCService/PCProgrammingPrototype/03DeviceImage", "DeviceImage Fail", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "DeviceImageFail.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01Test Case ID 1810723: [Avalon Service] Verify UpdateHDI API Skips HDI Update Wh" +
            "en Flash Write Protect Is LockedPermanent")]
        [NUnit.Framework.CategoryAttribute("DeviceImage")]
        public async global::System.Threading.Tasks.Task _01TestCaseID1810723AvalonServiceVerifyUpdateHDIAPISkipsHDIUpdateWhenFlashWriteProtectIsLockedPermanent()
        {
            string[] tagsOfScenario = new string[] {
                    "DeviceImage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01Test Case ID 1810723: [Avalon Service] Verify UpdateHDI API Skips HDI Update Wh" +
                    "en Flash Write Protect Is LockedPermanent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table11.AddRow(new string[] {
                            "2400801508"});
#line 8
 await testRunner.WhenAsync("Load a DFU image with  higher HDI version than the device, and set device Flash W" +
                        "rite Protect status to \"LockedPermanent\", and send a request to the UpdateHDI AP" +
                        "I", ((string)(null)), table11, "When ");
#line hidden
#line 11
 await testRunner.ThenAsync("API does not update  HDI in the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02Test Case ID 1810718: [Avalon Service] Verify WriteFDI API does not Write Image" +
            " When Optimized Programming Is Set to True")]
        [NUnit.Framework.CategoryAttribute("DeviceImage")]
        public async global::System.Threading.Tasks.Task _02TestCaseID1810718AvalonServiceVerifyWriteFDIAPIDoesNotWriteImageWhenOptimizedProgrammingIsSetToTrue()
        {
            string[] tagsOfScenario = new string[] {
                    "DeviceImage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02Test Case ID 1810718: [Avalon Service] Verify WriteFDI API does not Write Image" +
                    " When Optimized Programming Is Set to True", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table12.AddRow(new string[] {
                            "2400801508"});
#line 16
 await testRunner.WhenAsync("Load a valid DFU image, set isOptimizedProgramming to true, and send a request to" +
                        " WriteFDI API", ((string)(null)), table12, "When ");
#line hidden
#line 19
 await testRunner.ThenAsync("API does not write  image to the device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03Test Case ID 1810715: [Avalon Service] Verify WriteFDI API Returns Failed Preco" +
            "ndition When DFU Compatibility has not been Checked")]
        [NUnit.Framework.CategoryAttribute("DeviceImage")]
        public async global::System.Threading.Tasks.Task _03TestCaseID1810715AvalonServiceVerifyWriteFDIAPIReturnsFailedPreconditionWhenDFUCompatibilityHasNotBeenChecked()
        {
            string[] tagsOfScenario = new string[] {
                    "DeviceImage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03Test Case ID 1810715: [Avalon Service] Verify WriteFDI API Returns Failed Preco" +
                    "ndition When DFU Compatibility has not been Checked", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table13.AddRow(new string[] {
                            "2400801508"});
#line 24
 await testRunner.WhenAsync("Send a request to the WriteFDI API without performing DFU compatibility check", ((string)(null)), table13, "When ");
#line hidden
#line 27
 await testRunner.ThenAsync("API throws an exception with status \"Failed Precondition\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04Test Case ID 1810716: [Avalon Service] Verify WriteFDI API Returns Failed Preco" +
            "ndition When DFU Image Is Not Loaded")]
        [NUnit.Framework.CategoryAttribute("DeviceImage")]
        public async global::System.Threading.Tasks.Task _04TestCaseID1810716AvalonServiceVerifyWriteFDIAPIReturnsFailedPreconditionWhenDFUImageIsNotLoaded()
        {
            string[] tagsOfScenario = new string[] {
                    "DeviceImage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04Test Case ID 1810716: [Avalon Service] Verify WriteFDI API Returns Failed Preco" +
                    "ndition When DFU Image Is Not Loaded", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "SerialNumber"});
                table14.AddRow(new string[] {
                            "2400801508"});
#line 32
 await testRunner.WhenAsync("Send a request to the WriteFDI API without loading a DFU image", ((string)(null)), table14, "When ");
#line hidden
#line 35
 await testRunner.ThenAsync("API throws an exception with status the \"Failed Precondition\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
