// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace QuantumServicesAPI.Features.OCRDEVEnv
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OCR Service – DEV Environment (West Europe Region)")]
    public partial class OCRServiceDEVEnvironmentWestEuropeRegionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/OCRDEVEnv", "OCR Service – DEV Environment (West Europe Region)", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "OCRServiceDEVWestEurope.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01Test Case ID 1769058: Verify that the OCR service returns a list of all identif" +
            "ied character strings from the image provided")]
        [NUnit.Framework.CategoryAttribute("1769058")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _01TestCaseID1769058VerifyThatTheOCRServiceReturnsAListOfAllIdentifiedCharacterStringsFromTheImageProvided()
        {
            string[] tagsOfScenario = new string[] {
                    "1769058",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("01Test Case ID 1769058: Verify that the OCR service returns a list of all identif" +
                    "ied character strings from the image provided", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table25.AddRow(new string[] {
                            "PNGImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 8
 await testRunner.WhenAsync("Send the request with a correct image as input", ((string)(null)), table25, "When ");
#line hidden
#line 11
 await testRunner.AndAsync("Verify the response when correct image is inputted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
 await testRunner.ThenAsync("The response must contain a list of all the identified character strings.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02Test Case ID 1769060: Verify that the OCR service does not accept image with si" +
            "ze more than 256kb")]
        [NUnit.Framework.CategoryAttribute("1769060")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _02TestCaseID1769060VerifyThatTheOCRServiceDoesNotAcceptImageWithSizeMoreThan256Kb()
        {
            string[] tagsOfScenario = new string[] {
                    "1769060",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("02Test Case ID 1769060: Verify that the OCR service does not accept image with si" +
                    "ze more than 256kb", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table26.AddRow(new string[] {
                            "More256KBImage.jpg",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 17
 await testRunner.WhenAsync("Send a request with input as an image in PNG format with size more than 256kb", ((string)(null)), table26, "When ");
#line hidden
#line 20
 await testRunner.ThenAsync("Verify the response when image size is more than 256kb", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table27.AddRow(new string[] {
                            "Less256KBImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 21
 await testRunner.WhenAsync("Send a request with input as an image in PNG format with size less than 256kb", ((string)(null)), table27, "When ");
#line hidden
#line 24
 await testRunner.ThenAsync("Verify the response when image size is less than 256kb", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
 await testRunner.AndAsync("The response must contain a list of all the identified character strings.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03Test Case ID 1769076: Verify that the OCR service returns an empty list as resp" +
            "onse when a blurry image is passed as an input.")]
        [NUnit.Framework.CategoryAttribute("1769076")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _03TestCaseID1769076VerifyThatTheOCRServiceReturnsAnEmptyListAsResponseWhenABlurryImageIsPassedAsAnInput_()
        {
            string[] tagsOfScenario = new string[] {
                    "1769076",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("03Test Case ID 1769076: Verify that the OCR service returns an empty list as resp" +
                    "onse when a blurry image is passed as an input.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table28.AddRow(new string[] {
                            "BlurryPNGImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 30
 await testRunner.WhenAsync("Send the request with a blurry image as input", ((string)(null)), table28, "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("Verify the response when the inputted image is blurry", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
 await testRunner.AndAsync("The response must contain an empty list.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04Test Case ID 1776266: Verify that the OCR service returns an empty list as resp" +
            "onse when an invalid image is passed as an input.")]
        [NUnit.Framework.CategoryAttribute("1776266")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _04TestCaseID1776266VerifyThatTheOCRServiceReturnsAnEmptyListAsResponseWhenAnInvalidImageIsPassedAsAnInput_()
        {
            string[] tagsOfScenario = new string[] {
                    "1776266",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("04Test Case ID 1776266: Verify that the OCR service returns an empty list as resp" +
                    "onse when an invalid image is passed as an input.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table29.AddRow(new string[] {
                            "NoCharacters.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 39
 await testRunner.WhenAsync("Send the request with an invalid image (no characters)", ((string)(null)), table29, "When ");
#line hidden
#line 42
 await testRunner.ThenAsync("Verify the response when the inputted image is an invalid image (no characters)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
 await testRunner.AndAsync("The response must contain an empty list.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05Test Case ID 1780460: Verify that requests sent to the OCR Service with an inva" +
            "lid API key are rejected")]
        [NUnit.Framework.CategoryAttribute("1780460")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _05TestCaseID1780460VerifyThatRequestsSentToTheOCRServiceWithAnInvalidAPIKeyAreRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "1780460",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("05Test Case ID 1780460: Verify that requests sent to the OCR Service with an inva" +
                    "lid API key are rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "InvalidAPIkey"});
                table30.AddRow(new string[] {
                            "NoCharacters.png",
                            "dev",
                            "europe",
                            "1234567890"});
#line 48
 await testRunner.WhenAsync("Send a request to the WestEurope region using an invalid API key", ((string)(null)), table30, "When ");
#line hidden
#line 51
 await testRunner.ThenAsync("The request is rejected and returns a 401 Unauthorized error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06Test Case ID 1780459: Verify that requests without an API key for OCR Service a" +
            "re rejected")]
        [NUnit.Framework.CategoryAttribute("1780459")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _06TestCaseID1780459VerifyThatRequestsWithoutAnAPIKeyForOCRServiceAreRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "1780459",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("06Test Case ID 1780459: Verify that requests without an API key for OCR Service a" +
                    "re rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "InvalidAPIkey"});
                table31.AddRow(new string[] {
                            "PNGImage.png",
                            "dev",
                            "europe",
                            ""});
#line 56
 await testRunner.WhenAsync("Send a request to the WestEurope region without an API key", ((string)(null)), table31, "When ");
#line hidden
#line 59
 await testRunner.ThenAsync("The request is rejected and returns a 401 Unauthorized error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07Test Case ID 1780458: Verify that requests with a valid API key for OCR Service" +
            " are authenticated successfully")]
        [NUnit.Framework.CategoryAttribute("1780458")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _07TestCaseID1780458VerifyThatRequestsWithAValidAPIKeyForOCRServiceAreAuthenticatedSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "1780458",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("07Test Case ID 1780458: Verify that requests with a valid API key for OCR Service" +
                    " are authenticated successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table32.AddRow(new string[] {
                            "PNGImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 64
 await testRunner.WhenAsync("Send the request with a correct APIkey as input", ((string)(null)), table32, "When ");
#line hidden
#line 67
 await testRunner.AndAsync("Verify the response when correct APIkey is inputted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08Test Case ID 1769059: Verify that the OCR service only accepts supported image " +
            "formats (JPEG, PNG, BMP, PDF, and TIFF)")]
        [NUnit.Framework.CategoryAttribute("1769059")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _08TestCaseID1769059VerifyThatTheOCRServiceOnlyAcceptsSupportedImageFormatsJPEGPNGBMPPDFAndTIFF()
        {
            string[] tagsOfScenario = new string[] {
                    "1769059",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("08Test Case ID 1769059: Verify that the OCR service only accepts supported image " +
                    "formats (JPEG, PNG, BMP, PDF, and TIFF)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table33.AddRow(new string[] {
                            "JPEGImage.jpeg",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
                table33.AddRow(new string[] {
                            "PNGImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
                table33.AddRow(new string[] {
                            "BMPImage.bmp",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
                table33.AddRow(new string[] {
                            "PDFImage.pdf",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
                table33.AddRow(new string[] {
                            "TIFFImage.tiff",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 72
 await testRunner.WhenAsync("Send a request with input as an image in a supported format (JPEG, PNG, BMP, PDF," +
                        " TIFF) and verify the response and list of all the identified character strings", ((string)(null)), table33, "When ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table34.AddRow(new string[] {
                            "GIFImage.gif",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
                table34.AddRow(new string[] {
                            "WEBPImage.webp",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
                table34.AddRow(new string[] {
                            "SVGImage.svg",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 79
 await testRunner.AndAsync("Send a request with input as an image in an unsupported format (Ex: GIF, WEBP, SV" +
                        "G, etc.) and verify the 400 error returned", ((string)(null)), table34, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09Test Case ID 1780485: Verify the Response Time for OCR Service Under Normal Con" +
            "ditions")]
        [NUnit.Framework.CategoryAttribute("1780485")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _09TestCaseID1780485VerifyTheResponseTimeForOCRServiceUnderNormalConditions()
        {
            string[] tagsOfScenario = new string[] {
                    "1780485",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("09Test Case ID 1780485: Verify the Response Time for OCR Service Under Normal Con" +
                    "ditions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table35.AddRow(new string[] {
                            "PNGImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 88
 await testRunner.WhenAsync("Send a request to the OCR service under normal system load and verify the median " +
                        "response time", ((string)(null)), table35, "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10Test Case ID 1780470: Verify OCR Service Deployment in Each Cloud Region")]
        [NUnit.Framework.CategoryAttribute("1780470")]
        [NUnit.Framework.CategoryAttribute("DEV")]
        [NUnit.Framework.CategoryAttribute("WestEurope")]
        public async System.Threading.Tasks.Task _10TestCaseID1780470VerifyOCRServiceDeploymentInEachCloudRegion()
        {
            string[] tagsOfScenario = new string[] {
                    "1780470",
                    "DEV",
                    "WestEurope"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("10Test Case ID 1780470: Verify OCR Service Deployment in Each Cloud Region", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "ImageFormat",
                            "Env",
                            "Region",
                            "APIkey"});
                table36.AddRow(new string[] {
                            "PNGImage.png",
                            "dev",
                            "europe",
                            "39731117349c436792eca8513c7d2eb6"});
#line 95
 await testRunner.WhenAsync("OCR service is deployed to the WestEurope cloud region", ((string)(null)), table36, "When ");
#line hidden
#line 98
 await testRunner.AndAsync("OCR service should be operational in the WestEurope cloud region", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
